import "../globals.css";
import StoreProvider from "@/stores/StoreProvider";
import { store } from "@/stores/store";
import { login } from "@/stores/userSlice";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/routing";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) notFound();

  await store.dispatch(login({ id: 1, name: "Dirk or Rick" }));
  const user = await store.getState().user;
  setRequestLocale(locale);
  return (
    <html lang={locale}>
      <body
        className={
          "min-h-screen w-[100vw] flex flex-col justify-between bg-bgBase "
        }
      >
        <NextIntlClientProvider>
          <StoreProvider
            preloadedState={{
              user,
            }}
          >
            {children}
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
